# Generated by Django 5.0.1 on 2024-01-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
